### ISSUE TITLE
[Project] Web Services Documentation Project

### ISSUE THREAD

**Issue by particthistle** [particthistle/jcollaborate#1]
### Notes
Points of contact for API technical discussions:
George Wilson, Philip Walton, Eoin Oliver
Collaboration Repository: https://github.com/particthistle/jcollaborate

### Series Outline
Mark off checklist as articles are created and add links to drafts/related Article issues.

- [ ] Joomla Web Services 101 - Tokens, Testing and a Taste Test (August 2020) https://github.com/particthistle/jcollaborate/issues/2
- [ ] Introduction to API
- [ ] Examples of where it can be used - individual articles over time on each component that has an API section
- [ ] Case studies as it gets implemented for solutions (post J4 release)
- [ ] Using API with Zapier / IFTTT / Integromat to execute tasks using the API to distribute info to other sites
- [ ] Using API calls with Flutter to build Mobile Apps (JAB20 Session by Carlos Cámara Mora https://www.youtube.com/watch?v=iMdjTnf8gcs)
- [ ] Using API and the Joomla CLI?

### Resources

**Joomla Documentation** _Which needs enhancement at part of this series_
- [ ] https://docs.joomla.org/Category:Joomla!_Api
- [ ] API Usage Examples https://github.com/particthistle/jcollaborate/issues/3
- [ ] Good Examples of API Documentation https://github.com/particthistle/jcollaborate/issues/4
- [ ] Development notes on the Web Services API

**Joomla 4 API - JUG London**
https://www.youtube.com/embed/xCgUcyYHL4k?start=1218

- Intro: 0
- About this JUG: 15 seconds in
- Attendee introductions and chit chat: 37 seconds
- George Wilsons talk on the API: 20 minutes 18 seconds
- News: 1 hour 15 minutes
- Workshop: 1 hour 21 minutes
- Example of J3 site talking to a J4 site using J4 API and a J3 form: 1 hour 43 minutes
- Chitchat : 1 hour 59 minutes

**Research & Resources**

J4X Api Collection by Alexandre Elise
https://github.com/alexandreelise/j4x-api-collection

Chetan Madaan from JoomDev published 7 months ago this article together with a demo video :
https://www.joomdev.com/blog/entry/joomla-4-api-introduction
https://www.joomdev.com/blog/entry/token-based-authentication - Demonstrates Postman

Andy Gasman - Joomla CLI, Joomla Day UK - https://www.youtube.com/watch?v=w5ORPXt6W_o
http://www.ssofb.co.uk/slides/J_and_Beyond_2017/#/19

**Comment by particthistle** [comment]
Web Services in Joomla: A Roadmap
https://docs.google.com/document/d/1ZwmQeFWISPPv9o_a2GNeZUINmu95ja4R5KBxEr0zmCU/edit#heading=h.vmaf50k2yjvm
